# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e563ea2d26690faa88dee175ee017b5ed8258e2a957206922aa9a06ca7f1622cbe54fe9f23a85962afab0794773bedb1db1d94abaefe94a5104a4e4cb213f4ad

test:
  secret_key_base: b1fd0b2bd6d766e694afdfe6094960bdc5939d290824159c276ee17b5c2fae15e1fabf21bf56f11ce5988da4e508ce4db4b2aad8eabb29edaf39592ad060dc07

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
